name: Task 4

on:
  issues:
    types: [opened]
  workflow_dispatch: 
    inputs:
      team9_env:
        description: 'Select environment'     
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - test
        - prod

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - run: echo 'step1'
      - run: echo 'step2'
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps: 
        - uses: mscoutermarsh/cowsays-action@v1
          with:
          # What does the cow say?
            text: hey 
          # Color of your cow
            color: red
        - uses: actions/checkout@v3
        - name: Docker Login
          uses: docker/login-action@v1
          with:
            registry: ${{ secrets.ACR_LOGIN_SERVER }}
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}
        - uses: azure/webapps-deploy@v2
          with:
            app-name: 'team9-${{ inputs.team9_env }}'
            images: 'haduongdevopsreg.azurecr.io/wth/dotnetcoreapp:latest'